flowchart LR
  TOC_introduction["Introduction"]
  TOC_unit_1_integers_powers_and_roots["Unit 1 Integers, powers and roots"]
  TOC_unit_1_integers_powers_and_roots_1_1_arithmetic_with_integers["1.1 Arithmetic with integers"]
  TOC_unit_1_integers_powers_and_roots -.-> TOC_unit_1_integers_powers_and_roots_1_1_arithmetic_with_integers
  TOC_unit_1_integers_powers_and_roots_1_2_multiples_factors_and_primes["1.2 Multiples, factors and primes"]
  TOC_unit_1_integers_powers_and_roots -.-> TOC_unit_1_integers_powers_and_roots_1_2_multiples_factors_and_primes
  TOC_unit_1_integers_powers_and_roots_1_3_more_about_prime_numbers["1.3 More about prime numbers"]
  TOC_unit_1_integers_powers_and_roots -.-> TOC_unit_1_integers_powers_and_roots_1_3_more_about_prime_numbers
  TOC_unit_1_integers_powers_and_roots_1_4_powers_and_roots["1.4 Powers and roots"]
  TOC_unit_1_integers_powers_and_roots -.-> TOC_unit_1_integers_powers_and_roots_1_4_powers_and_roots
  TOC_unit_1_integers_powers_and_roots_unit_1_review["End-of-unit review"]
  TOC_unit_1_integers_powers_and_roots -.-> TOC_unit_1_integers_powers_and_roots_unit_1_review
  TOC_unit_2_sequences_expressions_and_formulae["Unit 2 Sequences, expressions and formulae"]
  TOC_unit_2_sequences_expressions_and_formulae_2_1_generating_sequences["2.1 Generating sequences"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_1_generating_sequences
  TOC_unit_2_sequences_expressions_and_formulae_2_2_finding_rules_for_sequences["2.2 Finding rules for sequences"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_2_finding_rules_for_sequences
  TOC_unit_2_sequences_expressions_and_formulae_2_3_using_the_nth_term["2.3 Using the nth term"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_3_using_the_nth_term
  TOC_unit_2_sequences_expressions_and_formulae_2_4_using_functions_and_mappings["2.4 Using functions and mappings"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_4_using_functions_and_mappings
  TOC_unit_2_sequences_expressions_and_formulae_2_5_constructing_linear_expressions["2.5 Constructing linear expressions"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_5_constructing_linear_expressions
  TOC_unit_2_sequences_expressions_and_formulae_2_6_deriving_and_using_formulae["2.6 Deriving and using formulae"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_2_6_deriving_and_using_formulae
  TOC_unit_2_sequences_expressions_and_formulae_unit_2_review["End-of-unit review"]
  TOC_unit_2_sequences_expressions_and_formulae -.-> TOC_unit_2_sequences_expressions_and_formulae_unit_2_review
  TOC_unit_3_place_value_ordering_and_rounding["Unit 3 Place value, ordering and rounding"]
  TOC_unit_3_place_value_ordering_and_rounding_3_1_multiplying_and_dividing_by_0_1_and_0_01["3.1 Multiplying and dividing by 0.1 and 0.01"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_1_multiplying_and_dividing_by_0_1_and_0_01
  TOC_unit_3_place_value_ordering_and_rounding_3_2_ordering_decimals["3.2 Ordering decimals"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_2_ordering_decimals
  TOC_unit_3_place_value_ordering_and_rounding_3_3_rounding["3.3 Rounding"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_3_rounding
  TOC_unit_3_place_value_ordering_and_rounding_3_4_adding_and_subtracting_decimals["3.4 Adding and subtracting decimals"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_4_adding_and_subtracting_decimals
  TOC_unit_3_place_value_ordering_and_rounding_3_5_dividing_decimals["3.5 Dividing decimals"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_5_dividing_decimals
  TOC_unit_3_place_value_ordering_and_rounding_3_6_multiplying_by_decimals["3.6 Multiplying by decimals"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_6_multiplying_by_decimals
  TOC_unit_3_place_value_ordering_and_rounding_3_7_dividing_by_decimals["3.7 Dividing by decimals"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_7_dividing_by_decimals
  TOC_unit_3_place_value_ordering_and_rounding_3_8_estimating_and_approximating["3.8 Estimating and approximating"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_3_8_estimating_and_approximating
  TOC_unit_3_place_value_ordering_and_rounding_unit_3_review["End-of-unit review"]
  TOC_unit_3_place_value_ordering_and_rounding -.-> TOC_unit_3_place_value_ordering_and_rounding_unit_3_review
  TOC_unit_4_length_mass_and_capacity["Unit 4 Length, mass and capacity"]
  TOC_unit_4_length_mass_and_capacity_4_1_choosing_suitable_units["4.1 Choosing suitable units"]
  TOC_unit_4_length_mass_and_capacity -.-> TOC_unit_4_length_mass_and_capacity_4_1_choosing_suitable_units
  TOC_unit_4_length_mass_and_capacity_4_2_kilometres_and_miles["4.2 Kilometres and miles"]
  TOC_unit_4_length_mass_and_capacity -.-> TOC_unit_4_length_mass_and_capacity_4_2_kilometres_and_miles
  TOC_unit_4_length_mass_and_capacity_unit_4_review["End-of-unit review"]
  TOC_unit_4_length_mass_and_capacity -.-> TOC_unit_4_length_mass_and_capacity_unit_4_review
  TOC_unit_5_angles["Unit 5 Angles"]
  TOC_unit_5_angles_5_1_parallel_lines["5.1 Parallel lines"]
  TOC_unit_5_angles -.-> TOC_unit_5_angles_5_1_parallel_lines
  TOC_unit_5_angles_5_2_explaining_angle_properties["5.2 Explaining angle properties"]
  TOC_unit_5_angles -.-> TOC_unit_5_angles_5_2_explaining_angle_properties
  TOC_unit_5_angles_5_3_solving_angle_problems["5.3 Solving angle problems"]
  TOC_unit_5_angles -.-> TOC_unit_5_angles_5_3_solving_angle_problems
  TOC_unit_5_angles_unit_5_review["End-of-unit review"]
  TOC_unit_5_angles -.-> TOC_unit_5_angles_unit_5_review
  TOC_unit_6_planning_and_collecting_data["Unit 6 Planning and collecting data"]
  TOC_unit_6_planning_and_collecting_data_6_1_collecting_data["6.1 Collecting data"]
  TOC_unit_6_planning_and_collecting_data -.-> TOC_unit_6_planning_and_collecting_data_6_1_collecting_data
  TOC_unit_6_planning_and_collecting_data_6_2_types_of_data["6.2 Types of data"]
  TOC_unit_6_planning_and_collecting_data -.-> TOC_unit_6_planning_and_collecting_data_6_2_types_of_data
  TOC_unit_6_planning_and_collecting_data_6_3_using_frequency_tables["6.3 Using frequency tables"]
  TOC_unit_6_planning_and_collecting_data -.-> TOC_unit_6_planning_and_collecting_data_6_3_using_frequency_tables
  TOC_unit_6_planning_and_collecting_data_unit_6_review["End-of-unit review"]
  TOC_unit_6_planning_and_collecting_data -.-> TOC_unit_6_planning_and_collecting_data_unit_6_review
  TOC_unit_7_fractions["Unit 7 Fractions"]
  TOC_unit_7_fractions_7_1_finding_equivalent_fractions_decimals_and_percentages["7.1 Finding equivalent fractions, decimals and percentages"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_1_finding_equivalent_fractions_decimals_and_percentages
  TOC_unit_7_fractions_7_2_converting_fractions_to_decimals["7.2 Converting fractions to decimals"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_2_converting_fractions_to_decimals
  TOC_unit_7_fractions_7_3_ordering_fractions["7.3 Ordering fractions"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_3_ordering_fractions
  TOC_unit_7_fractions_7_4_adding_and_subtracting_fractions["7.4 Adding and subtracting fractions"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_4_adding_and_subtracting_fractions
  TOC_unit_7_fractions_7_5_finding_fractions_of_a_quantity["7.5 Finding fractions of a quantity"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_5_finding_fractions_of_a_quantity
  TOC_unit_7_fractions_7_6_multiplying_an_integer_by_a_fraction["7.6 Multiplying an integer by a fraction"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_6_multiplying_an_integer_by_a_fraction
  TOC_unit_7_fractions_7_7_dividing_an_integer_by_a_fraction["7.7 Dividing an integer by a fraction"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_7_dividing_an_integer_by_a_fraction
  TOC_unit_7_fractions_7_8_multiplying_and_dividing_fractions["7.8 Multiplying and dividing fractions"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_7_8_multiplying_and_dividing_fractions
  TOC_unit_7_fractions_unit_7_review["End-of-unit review"]
  TOC_unit_7_fractions -.-> TOC_unit_7_fractions_unit_7_review
  TOC_unit_8_shapes_and_geometric_reasoning["Unit 8 Shapes and geometric reasoning"]
  TOC_unit_8_shapes_and_geometric_reasoning_8_1_recognising_congruent_shapes["8.1 Recognising congruent shapes"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_8_1_recognising_congruent_shapes
  TOC_unit_8_shapes_and_geometric_reasoning_8_2_identifying_symmetry_of_2d_shapes["8.2 Identifying symmetry of 2D shapes"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_8_2_identifying_symmetry_of_2d_shapes
  TOC_unit_8_shapes_and_geometric_reasoning_8_3_classifying_quadrilaterals["8.3 Classifying quadrilaterals"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_8_3_classifying_quadrilaterals
  TOC_unit_8_shapes_and_geometric_reasoning_8_4_drawing_nets_of_solids["8.4 Drawing nets of solids"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_8_4_drawing_nets_of_solids
  TOC_unit_8_shapes_and_geometric_reasoning_8_5_making_scale_drawings["8.5 Making scale drawings"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_8_5_making_scale_drawings
  TOC_unit_8_shapes_and_geometric_reasoning_unit_8_review["End-of-unit review"]
  TOC_unit_8_shapes_and_geometric_reasoning -.-> TOC_unit_8_shapes_and_geometric_reasoning_unit_8_review
  TOC_unit_9_simplifying_expressions_and_solving_equations["Unit 9 Simplifying expressions and solving equations"]
  TOC_unit_9_simplifying_expressions_and_solving_equations_9_1_collecting_like_terms["9.1 Collecting like terms"]
  TOC_unit_9_simplifying_expressions_and_solving_equations -.-> TOC_unit_9_simplifying_expressions_and_solving_equations_9_1_collecting_like_terms
  TOC_unit_9_simplifying_expressions_and_solving_equations_9_2_expanding_brackets["9.2 Expanding brackets"]
  TOC_unit_9_simplifying_expressions_and_solving_equations -.-> TOC_unit_9_simplifying_expressions_and_solving_equations_9_2_expanding_brackets
  TOC_unit_9_simplifying_expressions_and_solving_equations_9_3_constructing_and_solving_equations["9.3 Constructing and solving equations"]
  TOC_unit_9_simplifying_expressions_and_solving_equations -.-> TOC_unit_9_simplifying_expressions_and_solving_equations_9_3_constructing_and_solving_equations
  TOC_unit_9_simplifying_expressions_and_solving_equations_unit_9_review["End-of-unit review"]
  TOC_unit_9_simplifying_expressions_and_solving_equations -.-> TOC_unit_9_simplifying_expressions_and_solving_equations_unit_9_review
  TOC_unit_10_processing_and_presenting_data["Unit 10 Processing and presenting data"]
  TOC_unit_10_processing_and_presenting_data_10_1_calculating_statistics_from_discrete_data["10.1 Calculating statistics from discrete data"]
  TOC_unit_10_processing_and_presenting_data -.-> TOC_unit_10_processing_and_presenting_data_10_1_calculating_statistics_from_discrete_data
  TOC_unit_10_processing_and_presenting_data_10_2_calculating_statistics_from_grouped_or_continuous_data["10.2 Calculating statistics from grouped or continuous data"]
  TOC_unit_10_processing_and_presenting_data -.-> TOC_unit_10_processing_and_presenting_data_10_2_calculating_statistics_from_grouped_or_continuous_data
  TOC_unit_10_processing_and_presenting_data_10_3_using_statistics_to_compare_two_distributions["10.3 Using statistics to compare two distributions"]
  TOC_unit_10_processing_and_presenting_data -.-> TOC_unit_10_processing_and_presenting_data_10_3_using_statistics_to_compare_two_distributions
  TOC_unit_10_processing_and_presenting_data_unit_10_review["End-of-unit review"]
  TOC_unit_10_processing_and_presenting_data -.-> TOC_unit_10_processing_and_presenting_data_unit_10_review
  TOC_unit_11_percentages["Unit 11 Percentages"]
  TOC_unit_11_percentages_11_1_calculating_percentages["11.1 Calculating percentages"]
  TOC_unit_11_percentages -.-> TOC_unit_11_percentages_11_1_calculating_percentages
  TOC_unit_11_percentages_11_2_percentage_increases_and_decreases["11.2 Percentage increases and decreases"]
  TOC_unit_11_percentages -.-> TOC_unit_11_percentages_11_2_percentage_increases_and_decreases
  TOC_unit_11_percentages_11_3_finding_percentages["11.3 Finding percentages"]
  TOC_unit_11_percentages -.-> TOC_unit_11_percentages_11_3_finding_percentages
  TOC_unit_11_percentages_11_4_using_percentages["11.4 Using percentages"]
  TOC_unit_11_percentages -.-> TOC_unit_11_percentages_11_4_using_percentages
  TOC_unit_11_percentages_unit_11_review["End-of-unit review"]
  TOC_unit_11_percentages -.-> TOC_unit_11_percentages_unit_11_review
  TOC_unit_12_constructions["Unit 12 Constructions"]
  TOC_unit_12_constructions_12_1_drawing_circles_and_arcs["12.1 Drawing circles and arcs"]
  TOC_unit_12_constructions -.-> TOC_unit_12_constructions_12_1_drawing_circles_and_arcs
  TOC_unit_12_constructions_12_2_drawing_a_perpendicular_bisector["12.2 Drawing a perpendicular bisector"]
  TOC_unit_12_constructions -.-> TOC_unit_12_constructions_12_2_drawing_a_perpendicular_bisector
  TOC_unit_12_constructions_12_3_drawing_an_angle_bisector["12.3 Drawing an angle bisector"]
  TOC_unit_12_constructions -.-> TOC_unit_12_constructions_12_3_drawing_an_angle_bisector
  TOC_unit_12_constructions_12_4_constructing_triangles["12.4 Constructing triangles"]
  TOC_unit_12_constructions -.-> TOC_unit_12_constructions_12_4_constructing_triangles
  TOC_unit_12_constructions_unit_12_review["End-of-unit review"]
  TOC_unit_12_constructions -.-> TOC_unit_12_constructions_unit_12_review
  TOC_unit_13_graphs["Unit 13 Graphs"]
  TOC_unit_13_graphs_13_1_drawing_graphs_of_equations["13.1 Drawing graphs of equations"]
  TOC_unit_13_graphs -.-> TOC_unit_13_graphs_13_1_drawing_graphs_of_equations
  TOC_unit_13_graphs_13_2_equations_of_the_form_y_mx_c["13.2 Equations of the form y = mx + c"]
  TOC_unit_13_graphs -.-> TOC_unit_13_graphs_13_2_equations_of_the_form_y_mx_c
  TOC_unit_13_graphs_13_3_the_midpoint_of_a_line_segment["13.3 The midpoint of a line segment"]
  TOC_unit_13_graphs -.-> TOC_unit_13_graphs_13_3_the_midpoint_of_a_line_segment
  TOC_unit_13_graphs_13_4_graphs_in_real_life_contexts["13.4 Graphs in real-life contexts"]
  TOC_unit_13_graphs -.-> TOC_unit_13_graphs_13_4_graphs_in_real_life_contexts
  TOC_unit_13_graphs_unit_13_review["End-of-unit review"]
  TOC_unit_13_graphs -.-> TOC_unit_13_graphs_unit_13_review
  TOC_unit_14_ratio_and_proportion["Unit 14 Ratio and proportion"]
  TOC_unit_14_ratio_and_proportion_14_1_simplifying_ratios["14.1 Simplifying ratios"]
  TOC_unit_14_ratio_and_proportion -.-> TOC_unit_14_ratio_and_proportion_14_1_simplifying_ratios
  TOC_unit_14_ratio_and_proportion_14_2_sharing_in_a_ratio["14.2 Sharing in a ratio"]
  TOC_unit_14_ratio_and_proportion -.-> TOC_unit_14_ratio_and_proportion_14_2_sharing_in_a_ratio
  TOC_unit_14_ratio_and_proportion_14_3_solving_problems["14.3 Solving problems"]
  TOC_unit_14_ratio_and_proportion -.-> TOC_unit_14_ratio_and_proportion_14_3_solving_problems
  TOC_unit_14_ratio_and_proportion_unit_14_review["End-of-unit review"]
  TOC_unit_14_ratio_and_proportion -.-> TOC_unit_14_ratio_and_proportion_unit_14_review
  TOC_unit_15_probability["Unit 15 Probability"]
  TOC_unit_15_probability_15_1_the_probability_that_an_outcome_does_not_happen["15.1 The probability that an outcome does not happen"]
  TOC_unit_15_probability -.-> TOC_unit_15_probability_15_1_the_probability_that_an_outcome_does_not_happen
  TOC_unit_15_probability_15_2_equally_likely_outcomes["15.2 Equally likely outcomes"]
  TOC_unit_15_probability -.-> TOC_unit_15_probability_15_2_equally_likely_outcomes
  TOC_unit_15_probability_15_3_listing_all_possible_outcomes["15.3 Listing all possible outcomes"]
  TOC_unit_15_probability -.-> TOC_unit_15_probability_15_3_listing_all_possible_outcomes
  TOC_unit_15_probability_15_4_experimental_and_theoretical_probabilities["15.4 Experimental and theoretical probabilities"]
  TOC_unit_15_probability -.-> TOC_unit_15_probability_15_4_experimental_and_theoretical_probabilities
  TOC_unit_15_probability_unit_15_review["End-of-unit review"]
  TOC_unit_15_probability -.-> TOC_unit_15_probability_unit_15_review
  TOC_unit_16_position_and_movement["Unit 16 Position and movement"]
  TOC_unit_16_position_and_movement_16_1_transforming_shapes["16.1 Transforming shapes"]
  TOC_unit_16_position_and_movement -.-> TOC_unit_16_position_and_movement_16_1_transforming_shapes
  TOC_unit_16_position_and_movement_16_2_enlarging_shapes["16.2 Enlarging shapes"]
  TOC_unit_16_position_and_movement -.-> TOC_unit_16_position_and_movement_16_2_enlarging_shapes
  TOC_unit_16_position_and_movement_unit_16_review["End-of-unit review"]
  TOC_unit_16_position_and_movement -.-> TOC_unit_16_position_and_movement_unit_16_review
  TOC_unit_17_area_perimeter_and_volume["Unit 17 Area, perimeter and volume"]
  TOC_unit_17_area_perimeter_and_volume_17_1_the_area_of_a_triangle["17.1 The area of a triangle"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_1_the_area_of_a_triangle
  TOC_unit_17_area_perimeter_and_volume_17_2_the_areas_of_a_parallelogram_and_trapezium["17.2 The areas of a parallelogram and trapezium"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_2_the_areas_of_a_parallelogram_and_trapezium
  TOC_unit_17_area_perimeter_and_volume_17_3_the_area_and_circumference_of_a_circle["17.3 The area and circumference of a circle"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_3_the_area_and_circumference_of_a_circle
  TOC_unit_17_area_perimeter_and_volume_17_4_the_areas_of_compound_shapes["17.4 The areas of compound shapes"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_4_the_areas_of_compound_shapes
  TOC_unit_17_area_perimeter_and_volume_17_5_the_volumes_and_surface_areas_of_cuboids["17.5 The volumes and surface areas of cuboids"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_5_the_volumes_and_surface_areas_of_cuboids
  TOC_unit_17_area_perimeter_and_volume_17_6_using_nets_of_solids_to_work_out_surface_areas["17.6 Using nets of solids to work out surface areas"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_17_6_using_nets_of_solids_to_work_out_surface_areas
  TOC_unit_17_area_perimeter_and_volume_unit_17_review["End-of-unit review"]
  TOC_unit_17_area_perimeter_and_volume -.-> TOC_unit_17_area_perimeter_and_volume_unit_17_review
  TOC_unit_18_interpreting_and_discussing_results["Unit 18 Interpreting and discussing results"]
  TOC_unit_18_interpreting_and_discussing_results_18_1_interpreting_and_drawing_frequency_diagrams["18.1 Interpreting and drawing frequency diagrams"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_18_1_interpreting_and_drawing_frequency_diagrams
  TOC_unit_18_interpreting_and_discussing_results_18_2_interpreting_and_drawing_pie_charts["18.2 Interpreting and drawing pie charts"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_18_2_interpreting_and_drawing_pie_charts
  TOC_unit_18_interpreting_and_discussing_results_18_3_interpreting_and_drawing_line_graphs["18.3 Interpreting and drawing line graphs"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_18_3_interpreting_and_drawing_line_graphs
  TOC_unit_18_interpreting_and_discussing_results_18_4_interpreting_and_drawing_stem_and_leaf_diagrams["18.4 Interpreting and drawing stem-and-leaf diagrams"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_18_4_interpreting_and_drawing_stem_and_leaf_diagrams
  TOC_unit_18_interpreting_and_discussing_results_18_5_drawing_conclusions["18.5 Drawing conclusions"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_18_5_drawing_conclusions
  TOC_unit_18_interpreting_and_discussing_results_unit_18_review["End-of-unit review"]
  TOC_unit_18_interpreting_and_discussing_results -.-> TOC_unit_18_interpreting_and_discussing_results_unit_18_review
  TOC_introduction --> TOC_unit_1_integers_powers_and_roots
  TOC_unit_1_integers_powers_and_roots --> TOC_unit_2_sequences_expressions_and_formulae
  TOC_unit_2_sequences_expressions_and_formulae --> TOC_unit_3_place_value_ordering_and_rounding
  TOC_unit_3_place_value_ordering_and_rounding --> TOC_unit_4_length_mass_and_capacity
  TOC_unit_4_length_mass_and_capacity --> TOC_unit_5_angles
  TOC_unit_5_angles --> TOC_unit_6_planning_and_collecting_data
  TOC_unit_6_planning_and_collecting_data --> TOC_unit_7_fractions
  TOC_unit_7_fractions --> TOC_unit_8_shapes_and_geometric_reasoning
  TOC_unit_8_shapes_and_geometric_reasoning --> TOC_unit_9_simplifying_expressions_and_solving_equations
  TOC_unit_9_simplifying_expressions_and_solving_equations --> TOC_unit_10_processing_and_presenting_data
  TOC_unit_10_processing_and_presenting_data --> TOC_unit_11_percentages
  TOC_unit_11_percentages --> TOC_unit_12_constructions
  TOC_unit_12_constructions --> TOC_unit_13_graphs
  TOC_unit_13_graphs --> TOC_unit_14_ratio_and_proportion
  TOC_unit_14_ratio_and_proportion --> TOC_unit_15_probability
  TOC_unit_15_probability --> TOC_unit_16_position_and_movement
  TOC_unit_16_position_and_movement --> TOC_unit_17_area_perimeter_and_volume
  TOC_unit_17_area_perimeter_and_volume --> TOC_unit_18_interpreting_and_discussing_results
