import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import ClassroomCanvas from './ClassroomCanvas';
import type { Stroke } from '@/components/FullScreenWorkspace';
import { createHomework, getHomeworkSubmission, listClassHomeworks, saveHomeworkSubmission, updateHomeworkDeadline, uploadHomeworkAttachment, type Homework, type HomeworkAttachment } from '@/lib/homeworkService';
import { Calendar } from '@/components/ui/calendar';
import { Popover, PopoverContent, PopoverTrigger } from '@/components/ui/popover';
import HomeworkAssignmentPage from './HomeworkAssignmentPage';

const GREEN = '#10b981';
const card: React.CSSProperties = { background: '#1e293b', border: '1px solid #334155', borderRadius: 10, padding: 14 };
const input: React.CSSProperties = { padding: 9, borderRadius: 6, border: '1px solid #475569', background: '#0f172a', color: 'white', fontFamily: 'inherit' };

export default function ClassroomHomeworkView({ classId, role }: { classId: string; role: 'teacher' | 'student' }) {
  const { user } = useAuth();
  const [items, setItems] = useState<Homework[]>([]);
  const [loading, setLoading] = useState(true);
  const [creating, setCreating] = useState(false);
  const [selected, setSelected] = useState<Homework | null>(null);
  async function load() { setLoading(true); try { setItems(await listClassHomeworks(classId)); } finally { setLoading(false); } }
  useEffect(() => { void load(); }, [classId]);
  if (selected && user) return <HomeworkDetail homework={selected} role={role} studentId={user.uid} onBack={() => { setSelected(null); void load(); }} />;
  return <div>
    <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: 14 }}><h3 style={{ color: 'white', margin: 0 }}>Homeworks</h3>{role === 'teacher' && <button onClick={() => setCreating(true)} style={{ background: GREEN, color: 'white', border: 0, borderRadius: 7, padding: '8px 13px', fontWeight: 'bold', cursor: 'pointer' }}>+ New Homework</button>}</div>
    {creating && user && <CreateHomeworkModal classId={classId} teacherId={user.uid} onClose={() => setCreating(false)} onCreated={() => { setCreating(false); void load(); }} />}
    {loading ? <div style={{ color: '#64748b', padding: 25, textAlign: 'center' }}>Loading...</div> : items.length === 0 ? <div style={{ color: '#64748b', padding: 35, textAlign: 'center', border: '1px dashed #334155', borderRadius: 10 }}>No homework has been added yet.</div> : <div style={{ display: 'grid', gap: 10 }}>{items.map(homework => {
      const expired = Date.now() > new Date(homework.dueAt).getTime();
      return <div key={homework.id} onClick={() => setSelected(homework)} style={{ ...card, cursor: 'pointer', display: 'flex', alignItems: 'center', gap: 12 }}><span style={{ fontSize: 28 }}>📕</span><div style={{ flex: 1 }}><strong style={{ color: 'white' }}>{homework.title}</strong><div style={{ color: '#64748b', fontSize: 11 }}>{homework.fileName}</div><div style={{ color: expired ? '#f87171' : '#f59e0b', fontSize: 11, marginTop: 3 }}>Due {new Date(homework.dueAt).toLocaleString()}</div></div><span style={{ color: expired ? '#f87171' : GREEN, fontSize: 11, fontWeight: 'bold' }}>{expired ? 'CLOSED' : 'OPEN'}</span></div>;
    })}</div>}
  </div>;
}

function CreateHomeworkModal({ classId, teacherId, onClose, onCreated }: { classId: string; teacherId: string; onClose: () => void; onCreated: () => void }) {
  const [title, setTitle] = useState(''); const [dueAt, setDueAt] = useState(''); const [pdf, setPdf] = useState<File | null>(null); const [saving, setSaving] = useState(false); const [error, setError] = useState('');
  return <Overlay title="Create Homework" onClose={onClose}><div style={{ display: 'grid', gap: 12 }}><input value={title} onChange={e => setTitle(e.target.value)} placeholder="Homework name" style={{ ...input, padding: 11 }} /><DeadlinePicker value={dueAt} onChange={setDueAt} /><label style={{ padding: 14, borderRadius: 10, border: `1px dashed ${pdf ? GREEN : '#475569'}`, background: pdf ? `${GREEN}12` : '#0f172a', cursor: 'pointer', color: pdf ? 'white' : '#94a3b8', textAlign: 'center' }}><input hidden type="file" accept="application/pdf,.pdf" onChange={e => { setPdf(e.target.files?.[0] ?? null); setError(''); }} /><div style={{ fontSize: 24, marginBottom: 4 }}>📕</div>{pdf ? pdf.name : 'Click to select the homework PDF'}</label>{error && <div role="alert" style={{ padding: 9, borderRadius: 7, background: '#ef444422', border: '1px solid #ef444455', color: '#fca5a5', fontSize: 12 }}>{error}</div>}<button disabled={!pdf || !dueAt || saving} onClick={async () => { if (!pdf) return; setSaving(true); setError(''); try { await createHomework(classId, teacherId, title, new Date(dueAt).toISOString(), pdf); onCreated(); } catch (reason) { setError(reason instanceof Error ? reason.message : 'Homework upload failed.'); } finally { setSaving(false); } }} style={{ background: GREEN, color: 'white', border: 0, borderRadius: 9, padding: 11, fontWeight: 'bold', opacity: !pdf || !dueAt ? .5 : 1 }}>{saving ? 'Uploading PDF...' : 'Create Homework'}</button></div></Overlay>;
}

function HomeworkDetail({ homework, role, studentId, onBack }: { homework: Homework; role: 'teacher' | 'student'; studentId: string; onBack: () => void }) {
  return <HomeworkAssignmentPage homework={homework} role={role} userId={studentId} onBack={onBack} />;
}

function HomeworkSolver({ homework, studentId, onClose }: { homework: Homework; studentId: string; onClose: () => void }) {
  const [strokes, setStrokes] = useState<Stroke[]>([]); const [attachments, setAttachments] = useState<HomeworkAttachment[]>([]); const [submittedAt, setSubmittedAt] = useState<string | null>(null); const [tool, setTool] = useState<'pen' | 'eraser'>('pen'); const [busy, setBusy] = useState(false);
  const expired = Date.now() > new Date(homework.dueAt).getTime();
  useEffect(() => { void getHomeworkSubmission(homework.id, studentId).then(value => { if (value) { setStrokes(value.strokes || []); setAttachments(value.attachments || []); setSubmittedAt(value.submittedAt); } }); }, [homework.id, studentId]);
  async function persist(submit: boolean) { setBusy(true); try { const saved = await saveHomeworkSubmission(homework, studentId, strokes, attachments, submit); setSubmittedAt(saved.submittedAt); } finally { setBusy(false); } }
  return <div style={{ position: 'fixed', inset: 0, zIndex: 10000, background: 'white', display: 'flex', flexDirection: 'column' }}><div style={{ padding: 8, background: '#f8fafc', borderBottom: '1px solid #dbe3ee', display: 'flex', gap: 7, alignItems: 'center', flexWrap: 'wrap' }}><button onClick={onClose} style={input}>← Back</button><strong style={{ color: '#0f172a', flex: 1 }}>{homework.title}</strong><button onClick={() => setTool('pen')} style={{ ...input, background: tool === 'pen' ? '#dbeafe' : 'white', color: '#0f172a' }}>✏️ Pen</button><button onClick={() => setTool('eraser')} style={{ ...input, background: tool === 'eraser' ? '#fee2e2' : 'white', color: '#0f172a' }}>🧹 Eraser</button>{!expired && <label style={{ ...input, background: 'white', color: '#0f172a', cursor: 'pointer' }}><input hidden type="file" multiple onChange={async e => { const files = [...(e.target.files ?? [])]; const uploaded = await Promise.all(files.map(file => uploadHomeworkAttachment(homework, studentId, file))); setAttachments(old => [...old, ...uploaded]); }} />📎 Upload files</label>}{!expired && <button disabled={busy} onClick={() => void persist(false)} style={input}>Save Draft</button>}{!expired && <button disabled={busy} onClick={() => void persist(true)} style={{ background: GREEN, color: 'white', border: 0, borderRadius: 7, padding: 9, fontWeight: 'bold' }}>{submittedAt ? 'Submit Again' : 'Submit'}</button>}</div>{attachments.length > 0 && <div style={{ padding: '6px 10px', background: '#f8fafc', display: 'flex', gap: 6, flexWrap: 'wrap' }}>{attachments.map((file, index) => <span key={file.path} style={{ fontSize: 11, color: '#334155', border: '1px solid #cbd5e1', borderRadius: 6, padding: '4px 7px' }}><a href={file.url} target="_blank" rel="noreferrer">{file.name}</a>{!expired && <button onClick={() => setAttachments(old => old.filter((_, i) => i !== index))} style={{ border: 0, background: 'none', color: '#ef4444' }}>×</button>}</span>)}</div>}<div style={{ flex: 1, minHeight: 0, overflow: 'auto' }}><ClassroomCanvas pageWidth={794} pageHeight={1123} strokes={strokes} onStrokeAdd={stroke => setStrokes(old => [...old, stroke])} onStrokeRemove={id => setStrokes(old => old.filter(stroke => stroke.id !== id))} color="#1e293b" strokeWidth={3} tool={tool} disabled={expired} style={{ width: '100%', height: 'auto', minHeight: '100%' }} /></div></div>;
}

function Overlay({ title, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) { return <div style={{ position: 'fixed', inset: 0, zIndex: 200, background: 'rgba(0,0,0,.65)', display: 'grid', placeItems: 'center', padding: 20 }}><div style={{ ...card, width: 'min(420px, 100%)' }}><div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 14 }}><strong style={{ color: 'white' }}>{title}</strong><button onClick={onClose} style={{ border: 0, background: 'none', color: '#94a3b8' }}>×</button></div>{children}</div></div>; }

function localValue(date: Date): string { const offset = date.getTimezoneOffset() * 60000; return new Date(date.getTime() - offset).toISOString().slice(0, 16); }
function DeadlinePicker({ value, onChange }: { value: string; onChange: (value: string) => void }) {
  const selected = value ? new Date(value) : undefined;
  const setPreset = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); date.setHours(0, 0, 0, 0); onChange(localValue(date)); };
  const selectDay = (day?: Date) => { if (!day) return; const current = selected ?? new Date(); day.setHours(current.getHours(), current.getMinutes(), 0, 0); onChange(localValue(day)); };
  const setTime = (hour: number, minute: number) => { const date = selected ?? new Date(); date.setHours(hour, minute, 0, 0); onChange(localValue(date)); };
  return <div style={{ display: 'grid', gap: 9, padding: 11, borderRadius: 11, background: '#0b1324', border: '1px solid #334155' }}><div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center' }}><strong style={{ color: '#e2e8f0', fontSize: 12 }}>Submission deadline</strong>{selected && <span style={{ color: GREEN, fontSize: 10, fontWeight: 'bold' }}>✓ DATE SELECTED</span>}</div><div style={{ display: 'grid', gridTemplateColumns: 'minmax(0, 1fr) 120px', gap: 7 }}>
    <Popover><PopoverTrigger asChild><button type="button" style={{ padding: 10, borderRadius: 8, border: `1px solid ${selected ? '#3b82f688' : '#475569'}`, background: selected ? '#3b82f615' : '#111827', color: 'white', textAlign: 'left', cursor: 'pointer' }}><span style={{ display: 'block', color: '#93c5fd', fontSize: 10, fontWeight: 'bold', marginBottom: 3 }}>📅 DATE</span>{selected ? selected.toLocaleDateString(undefined, { weekday: 'short', month: 'short', day: 'numeric', year: 'numeric' }) : 'Choose a day'}</button></PopoverTrigger><PopoverContent align="start" className="w-auto overflow-hidden rounded-xl border-slate-700 bg-slate-950 p-0 text-slate-100 shadow-2xl"><Calendar mode="single" selected={selected} onSelect={selectDay} disabled={{ before: new Date() }} initialFocus /></PopoverContent></Popover>
    <Popover><PopoverTrigger asChild><button type="button" style={{ padding: 10, borderRadius: 8, border: `1px solid ${selected ? '#8b5cf688' : '#475569'}`, background: selected ? '#8b5cf615' : '#111827', color: 'white', textAlign: 'left', cursor: 'pointer' }}><span style={{ display: 'block', color: '#c4b5fd', fontSize: 10, fontWeight: 'bold', marginBottom: 3 }}>🕐 TIME</span>{selected ? selected.toLocaleTimeString([], { hour: '2-digit', minute: '2-digit' }) : 'Choose'}</button></PopoverTrigger><PopoverContent align="end" className="w-64 rounded-xl border-slate-700 bg-slate-950 text-slate-100 shadow-2xl"><div style={{ color: '#94a3b8', fontSize: 11, marginBottom: 8 }}>Choose hour and minute</div><div style={{ display: 'flex', gap: 8 }}><select aria-label="Hour" value={selected?.getHours() ?? 0} onChange={event => setTime(Number(event.target.value), selected?.getMinutes() ?? 0)} style={{ ...input, flex: 1, padding: 10 }}>{Array.from({ length: 24 }, (_, hour) => <option key={hour} value={hour}>{String(hour).padStart(2, '0')} h</option>)}</select><span style={{ color: '#64748b', alignSelf: 'center', fontWeight: 'bold' }}>:</span><select aria-label="Minute" value={selected?.getMinutes() ?? 0} onChange={event => setTime(selected?.getHours() ?? 0, Number(event.target.value))} style={{ ...input, flex: 1, padding: 10 }}>{Array.from({ length: 60 }, (_, minute) => <option key={minute} value={minute}>{String(minute).padStart(2, '0')}</option>)}</select></div></PopoverContent></Popover>
  </div><div style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 7 }}><button type="button" onClick={() => setPreset(1)} style={{ padding: 9, borderRadius: 8, border: '1px solid #334155', background: '#172033', color: '#cbd5e1', cursor: 'pointer', fontSize: 11 }}><span style={{ color: '#fbbf24' }}>☀</span> Tomorrow <small style={{ color: '#64748b' }}>00:00</small></button><button type="button" onClick={() => setPreset(7)} style={{ padding: 9, borderRadius: 8, border: '1px solid #334155', background: '#172033', color: '#cbd5e1', cursor: 'pointer', fontSize: 11 }}><span style={{ color: '#a78bfa' }}>◷</span> Next week <small style={{ color: '#64748b' }}>00:00</small></button></div></div>;
}
